name: Build Windows
on:
  push:
  release:
    types: [created]
jobs:
  build:
    runs-on: windows-2016
    env:
      MSYS2_PATH_TYPE: inherit
      COMMIT_RELEASE_CAIRO: fda1f07bdf8cc187eb81b0cb877e394ef74bdfaa
      PANGO_VERSION: "1.47.0"
      FRIBIDI_VERSION: "1.0.10"
      HARFBUZZ_VERSION: "2.7.2"
      GLIB_VERSION: "2.67.0"
      WORKSPACE: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - name: Download and Copy Necessary Files
        shell: powershell
        run: ci/win/download.ps1
      - name: Build x86
        run: |
          cd x86
          $prevPath = $env:PATH
          & "$env:WORKSPACE\ci\win\build.ps1" 32
          $env:PATH=$prevPath
          cd ../
      - name: Build x64
        run: |
          cd x64
          $prevPath = $env:PATH
          & "$env:WORKSPACE\ci\win\build.ps1" 64
          $env:PATH = $prevPath
          cd ../
      - name: Pack Assets
        run: |
          7z a pango-build-x86.zip C:\build\x86\*
          7z a pango-build-x64.zip C:\build\amd64\*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: final-build
          path: "*.zip"

