name: Build Linux
on:
  push:
    branches: [ master ]
jobs:
  build:    
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_${{matrix.container}}
    env:
      WORKSPACE: ${{ github.workspace }}
    strategy:
      fail-fast: false
      matrix:
        container: ["x86_64","i686"]
    steps:    
      - name: Download Repo
        run: |
          curl -L https://github.com/naveen521kk/pango-cairo-build/archive/master.zip -o clone.zip
          yum install -y p7zip
          7z x clone.zip
      - name: Build
        run: |
          python3 ci/linux-build.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: final-build
          path: cairo_release.zip

