name: Build Pango
on:
  push:
jobs:
  build-windows:
    name: Build Pango On Windows
    runs-on: windows-2016
    env:
      MSYS2_PATH_TYPE: inherit
      WORKSPACE: ${{ github.workspace }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup-Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Update Version
        run: |
          cd updator
          pip install -r requirements.txt
          python main.py
      - name: Download and Copy Necessary Files
        shell: powershell
        run: ci/win/download.ps1
      - name: Build x86
        run: |
          cd x86
          $prevPath = $env:PATH
          & "$env:WORKSPACE\ci\win\build.ps1" 32
          $env:PATH=$prevPath
          cd ../
      - name: Build x64
        run: |
          cd x64
          $prevPath = $env:PATH
          & "$env:WORKSPACE\ci\win\build.ps1" 64
          $env:PATH = $prevPath
          cd ../
      - name: Pack Assets
        run: |
          7z a pango-build-x86.zip C:\build\x86\*
          7z a pango-build-x64.zip C:\build\amd64\*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pango-build-x86
          path: pango-build-x86.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pango-build-x64
          path: pango-build-x64.zip
