name: Build Windows
on:
  push:
    branches: [ master ]
jobs:
  build:    
    runs-on: windows-2016
    steps:    
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
