name: Build Linux
on:
  push:
jobs:
  build:    
    runs-on: ubuntu-16.04
    container: ${{matrix.container}}/ubuntu
    env:
      WORKSPACE: ${{ github.workspace }}
      arch: ${{matrix.container}}
    strategy:
      fail-fast: false
      matrix:
        container: ["amd64","i686"]
    steps:    
      - name: Download Repo
        run: |
          apt update
          apt upgrade
          apt install git
          apt install curl
          apt install python3-dev python3-pip
          apt
          curl -L https://github.com/naveen521kk/pango-build/archive/master.zip -o clone.zip
          unzip clone.zip
          mv pango-build-* pango-cairo
      - name: Build
        run: |
          python3 -m pip install -U pip
          python3 -m pip install requests
          /opt/python/cp38-cp38/bin/python pango-cairo/ci/linux-build.py $arch
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: final-build
          path: cairo_release.zip

