name: Build Linux
on:
  push:
    branches: [ master ]
jobs:
  build:    
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2010_${{matrix.container}}
    env:
      WORKSPACE: ${{ github.workspace }}
      arch: ${{matrix.container}}
    strategy:
      fail-fast: false
      matrix:
        container: ["x86_64","i686"]
    steps:    
      - name: Download Repo
        run: |
          curl -L https://github.com/naveen521kk/pango-cairo-build/archive/master.zip -o clone.zip
          unzip clone.zip
          mv pango-cairo-build-* pango-cairo
      - name: Build
        run: |
          /opt/python/cp38-cp38/bin/python -m pip install certifi
          /opt/python/cp38-cp38/bin/python pango-cairo/ci/linux-build.py $arch
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: final-build
          path: cairo_release.zip

