name: Build Linux
on:
  push:
jobs:
  build-x64:    
    runs-on: ubuntu-16.04
    env:
      WORKSPACE: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v2
      - name: Install expat
        run: |
          sudo apt-get install -y gperf 
      - name: Setup-Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build
        run: |
          python3 -m pip install -U pip
          python3 -m pip install requests
          python3 ci/linux-build.py amd64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: final-build
          path: dist
      - run: curl -L https://gist.github.com/naveen521kk/8e986f335716aff08a11b3870376e609/raw/35c6c319b93c4976eee3b6e5a5de5cd9a5bb2318/text2svg.py -o /home/some.py
      - uses: docker://python-slim:3.8.6
        run: |
          pip install text2svg
          python /home/some.py
          
