name: Build Linux
on:
  push:
jobs:
  container:
    runs-on: ubuntu-latest
    container: python:3.6
    steps:
      - name: Download Assets
        run: |
          mkdir -p "/home/runner/work/pango-build/pango-build"
          cd "/home/runner/work/pango-build/pango-build"
          pip install requests
          python -c "import requests;a=requests.get('https://github.com/naveen521kk/pango-build/releases/download/v1.47.0/pango-build-linux.zip');b=open('pango.zip','wb');b.write(a.content)"
          python -m zipfile -e pango.zip pango
          apt-get -y update
          apt-get install -y build-essential pkg-config
          mv pango/* .

      - name: Install Text2SVG
        run: |
          export PATH="/home/runner/work/pango-build/pango-build/dist/amd64/pkg-config/bin:$PATH"
          export PKG_CONFIG_PATH="/home/runner/work/pango-build/pango-build/dist/amd64/lib/x86_64-linux-gnu/pkgconfig"
          pip install Cython
          pip install text2svg --no-binary :all:
  
