name: Build Linux
on:
  push:
jobs:
  container:
    runs-on: ubuntu-latest
    container: python:3.6-slim
    steps:
      - name: Download Assets
        run: |
          mkdir -p "/home/runner/work/pango-build/pango-build"
          cd "/home/runner/work/pango-build/pango-build"
          pip install requests
          python -c "import requests;a=requests.get('https://github.com/naveen521kk/pango-build/releases/download/v1.47.0/pango-build-linux.zip');b=open('pango.zip','wb');b.write(a.content)"
          7z x pango-build-linux.zip
      - name: Install Text2SVG
        run: |
          export PKG_CONFIG_PATH="/home/runner/work/pango-build/pango-build/dist/amd64/lib/x86_64-linux-gnu/pkgconfig"
          pip install Cython
          pip install text2svg --no-binary :all:
  
